apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
  name: efs-jenkins-sc
parameters:
  basePath: /dynamic
  directoryPerms: "700"
  ensureUniqueDirectory: "true"
  fileSystemId: fs-0abd7eff4f3d61720
  gid: "1000"
  provisioningMode: efs-ap
  reuseAccessPoint: "false"
  subPathPattern: ${.PVC.name}
  uid: "1000"
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
